# Generated by Django 3.2 on 2021-12-29 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TMHVehicleapp', '0002_role_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_master',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
