# Generated by Django 3.2 on 2021-12-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHVehicleapp', '0004_alter_role_master_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver_details',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
