# Generated by Django 3.2 on 2021-12-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHVehicleapp', '0005_auto_20211229_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_id',
            field=models.IntegerField(null=True),
        ),
    ]
