# Generated by Django 3.2 on 2021-12-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHVehicleapp', '0006_alter_booking_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
