# Generated by Django 3.2 on 2022-01-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHVehicleapp', '0011_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
