# Generated by Django 3.2 on 2022-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHVehicleapp', '0012_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Normal Vehicle', 'Normal Vehicle'), ('Ambulance', 'Ambulance')], max_length=50),
        ),
    ]
